# Generated by Django 2.0.6 on 2018-06-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snitch_details',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
