# Generated by Django 2.0.6 on 2018-06-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snitches', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snitch_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snitches.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='snitch_details',
            name='owner',
        ),
        migrations.AddField(
            model_name='snitch_group',
            name='snitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snitches.Snitch_Details'),
        ),
    ]
