# Generated by Django 2.0.6 on 2018-06-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snitches', '0005_token_webhooktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_member',
            name='permission',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='owner', max_length=6),
        ),
    ]
