# Generated by Django 2.0.6 on 2018-06-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snitches', '0006_auto_20180611_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_member',
            name='permission',
            field=models.CharField(choices=[('ad', 'ad'), ('me', 'me')], default='me', max_length=2),
        ),
    ]
