# Generated by Django 2.0.6 on 2018-06-17 19:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snitches', '0009_auto_20180617_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktransaction',
            name='body',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='webhooktransaction',
            name='status',
            field=models.CharField(choices=[('UN', 'Unprocessed'), ('PR', 'Processed'), ('ER', 'Error')], default='UN', max_length=250),
        ),
    ]
