# Generated by Django 2.0.6 on 2018-06-27 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snitches', '0010_auto_20180617_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_Member',
            new_name='GroupMember',
        ),
        migrations.RenameModel(
            old_name='Snitch_Group',
            new_name='SnitchGroup',
        ),
        migrations.RenameModel(
            old_name='Snitch_Record',
            new_name='SnitchRecord',
        ),
    ]
