# Generated by Django 2.0.6 on 2018-06-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snitches', '0011_auto_20180627_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snitchrecord',
            name='type',
            field=models.CharField(choices=[('Et', 'Entered'), ('Li', 'Logged in'), ('Lo', 'Logged out')], default=None, max_length=2),
        ),
    ]
