# Generated by Django 2.0.6 on 2018-08-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snitches', '0012_auto_20180628_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
